#!/bin/bash
set -e
echo "Начало деплоя"

git pull

source venv/bin/activate
pip install -r requirements.txt

npm ci --dev
./node_modules/.bin/parcel build bundles-src/index.js --dist-dir bundles --public-url="./" --no-autoinstall --no-cache

python manage.py collectstatic --noinput
python manage.py migrate

systemctl restart star_burger.service
systemctl reload nginx

echo "Успешно"
