#!/bin/bash
set -e
echo "Начало деплоя"
echo "тест"

git pull

source venv/bin/activate
pip install -r requirements.txt

npm ci --dev
./node_modules/.bin/parcel build bundles-src/index.js --dist-dir bundles --public-url="./" --no-autoinstall --no-cache

python manage.py collectstatic --noinput
python manage.py migrate --noinput

systemctl restart star_burger.service
systemctl reload nginx

echo "Отправляется уведомление о деплое в rollbar"
source .env
COMMIT_HASH=$(git rev-parse HEAD)

curl --request POST \
     --url https://api.rollbar.com/api/1/deploy \
     --header "X-Rollbar-Access-Token: $ROLLBAR_DEPLOY_TOKEN" \
     --header 'accept: application/json' \
     --header 'content-type: application/json' \
     --data '{
  "environment": "production",
  "status": "succeeded",
  "revision": "'"$COMMIT_HASH"'"
}'

echo "Уведомление в rollbar отправлено"

echo "Успешно"
