# Generated by Django 5.2.14 on 2026-05-27 19:25

from django.db import migrations


def fill_prices(apps, shema_editor):
    OrderProduct = apps.get_model('foodcartapp', 'OrderProduct')

    order_products = OrderProduct.objects.select_related('product').iterator()

    for position in order_products:
        position.price = position.product.price
        position.save()


class Migration(migrations.Migration):
    dependencies = [
        ('foodcartapp', '0039_orderproduct_price'),
    ]

    operations = [migrations.RunPython(fill_prices)]
