# Generated by Django 5.2.14 on 2026-05-28 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0040_fill_order_product_prices'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('NEW', 'Новый'), ('COOKING', 'Готовится'), ('DELIVER', 'Доставляется'), ('COMPLETE', 'Заверншен')], default='NEW', max_length=20),
        ),
    ]
