# Generated by Django 5.2.14 on 2026-05-28 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0041_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('NEW', 'Новый'), ('COOKING', 'Готовится'), ('DELIVER', 'Доставляется'), ('COMPLETE', 'Завершен')], db_index=True, default='NEW', max_length=20),
        ),
    ]
