# Generated by Django 5.2.14 on 2026-05-28 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0044_order_called_at_order_created_at_order_delivered_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('NON_CASH', 'Безналичный'), ('CASH', 'Наличными')], max_length=20, null=True, verbose_name='Способо оплаты'),
        ),
    ]
