# Generated by Django 5.2.14 on 2026-05-28 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0045_order_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('NON_CASH', 'Безналичный'), ('CASH', 'Наличными')], db_index=True, max_length=20, null=True, verbose_name='Способо оплаты'),
        ),
    ]
