# Generated by Django 5.2.14 on 2026-05-31 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0046_alter_order_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cooked_orders', to='foodcartapp.restaurant', verbose_name='Готовящий ресторан'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('NON_CASH', 'Безналичный'), ('CASH', 'Наличными')], db_index=True, max_length=20, null=True, verbose_name='Способ оплаты'),
        ),
    ]
