# Generated by Django 5.2.14 on 2026-05-28 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0042_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Комментарий к заказу'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('NEW', 'Новый'), ('COOKING', 'Готовится'), ('DELIVER', 'Доставляется'), ('COMPLETE', 'Завершен')], db_index=True, default='NEW', max_length=20, verbose_name='Статус заказа'),
        ),
    ]
